matter-labs/zksync-os

Cargo.toml
api/Cargo.toml
callable_oracles/Cargo.toml
circuit_test_program/Cargo.toml
crypto/Cargo.toml
crypto/src/blake2s/test_program/Cargo.toml
cycle_marker/Cargo.toml
oracle_provider/Cargo.toml
tests/rig/Cargo.toml
zksync_os/Cargo.toml
zksync_os_runner/Cargo.toml

chore: pin airbender version

---

LICENSE-APACHE
LICENSE-MIT
basic_system/LICENSE-APACHE
basic_system/LICENSE-MIT
evm_interpreter/LICENSE-APACHE
evm_interpreter/LICENSE-MIT
supporting_crates/solidity_abi/LICENSE-APACHE
supporting_crates/solidity_abi/LICENSE-MIT
supporting_crates/solidity_abi_derive/LICENSE-APACHE
supporting_crates/solidity_abi_derive/LICENSE-MIT

chore: Update LICENSE-APACHE

---

basic_bootloader/src/bootloader/constants.rs
basic_bootloader/src/bootloader/process_transaction.rs

fix: use constant native price for l1 tx

---

basic_bootloader/src/bootloader/constants.rs
basic_bootloader/src/bootloader/process_transaction.rs
docs/double_resource_accounting.md
docs/overview.md

docs: Add description of resource accounting to docs

---

basic_bootloader/src/bootloader/account_models/contract.rs
basic_bootloader/src/bootloader/account_models/eoa.rs
basic_bootloader/src/bootloader/constants.rs
basic_bootloader/src/bootloader/process_transaction.rs
basic_bootloader/src/bootloader/runner.rs
crypto/Cargo.toml
evm_interpreter/src/native_resource_constants.rs

chore: remove outdated TODOs

---

zk_ee/src/common_structs/new_preimages_publication_storage.rs

Remove it since it is used only in tests and a bit confusing.

fix: Remove net pubdata used from new preimages cache

---

basic_system/src/system_implementation/flat_storage_model/account_cache.rs
basic_system/src/system_implementation/flat_storage_model/mod.rs
basic_system/src/system_implementation/flat_storage_model/storage_cache.rs
basic_system/src/system_implementation/system/io_subsystem.rs
zk_ee/src/common_structs/cache_record.rs
zk_ee/src/common_structs/history_map/element_pool.rs
zk_ee/src/common_structs/history_map/element_with_history.rs
zk_ee/src/common_structs/history_map/mod.rs
zk_ee/src/common_structs/new_preimages_publication_storage.rs
zk_ee/tests/playground.rs

Cleanup, adding tests, removing TODOs.

feat: Remaining TODOs in history map

---

tests/instances/eth_runner/src/block_hashes.rs
tests/instances/eth_runner/src/main.rs
tests/instances/eth_runner/src/post_check.rs
tests/instances/eth_runner/src/prestate.rs
tests/rig/src/chain.rs

test: more fixes and block hash suporty for eth runner

---

system_hooks/src/contract_deployer.rs

To make diff smaller with Era and allow the same contract to be used for the upgrades

feat: Allow complex upgrader to do force deploys

---

docs/README.md
docs/proving_ethereum.md

Added docs with instructions on how to prove ethereum.

docs: proving ethereum

---

docs/proving_ethereum.md

Updated docs on proving Ethereum. 
Mostly minor fixes. Wrote the CPU proving command explicitly.

docs: update proving ethereum

---

.github/workflows/bench.yml

fix: use expected name for evm replay binary in bench

---

evm_interpreter/src/instructions/heap.rs

feat(EVM): [Experimental] Optimize MLOAD

---

tests/instances/eth_runner/src/block.rs
tests/instances/eth_runner/src/calltrace.rs
tests/instances/eth_runner/src/live_run/mod.rs
tests/instances/eth_runner/src/single_run.rs

feat: skip txs with unsupported precompiles in runner

---

.github/workflows/ci.yml

fix: run evm tester in release mode

---

api/src/lib.rs
forward_system/src/run/mod.rs

fix: Bump simulator cycle limit

---

system_hooks/src/l2_base_token.rs

fix: sender of log in base token

---

api/Cargo.toml
api/src/helpers.rs
tests/rig/src/utils.rs

refactor: get rid of ethers and zksync_types in api

---

basic_bootloader/src/bootloader/account_models/contract.rs
basic_bootloader/src/bootloader/account_models/eoa.rs
basic_bootloader/src/bootloader/paymaster_helper.rs
basic_bootloader/src/bootloader/process_transaction.rs
basic_bootloader/src/bootloader/run_single_interaction.rs
basic_bootloader/src/bootloader/runner.rs
basic_bootloader/src/bootloader/supported_ees.rs
evm_interpreter/src/ee_trait_impl.rs
evm_interpreter/src/errors.rs
evm_interpreter/src/instructions/host.rs
evm_interpreter/src/interpreter.rs
evm_interpreter/src/lib.rs
forward_system/src/system/tracers/call_tracer.rs
forward_system/src/system/tracers/evm_opcodes_logger.rs
system_hooks/src/contract_deployer.rs
system_hooks/src/l1_messenger.rs
system_hooks/src/l2_base_token.rs
system_hooks/src/lib.rs
system_hooks/src/precompiles.rs
zk_ee/src/system/execution_environment/call_params.rs
zk_ee/src/system/execution_environment/environment_state.rs
zk_ee/src/system/execution_environment/interaction_params.rs
zk_ee/src/system/execution_environment/mod.rs
zk_ee/src/system/tracer/mod.rs

feat: Simplify runner <-> EE interaction

---

api/Cargo.toml
api/src/helpers.rs

Ditto, `full` brings in a lot of stuff by default that we don't actually need

chore(api): reduce alloy features

---

zk_ee/src/system/metadata.rs

fix: Update comment for block hashes

---

.github/workflows/ci.yml
Cargo.toml
tests/instances/eth_runner/src/calltrace.rs
tests/instances/transactions/src/lib.rs

feat: update interface
